remove most of the GPG email section
CivicActions/guidebook pull request #1055
Opened 2023-02-10 04:00 UTC by openprivacy

2023-02-15 23:24 UTC, dmundra approved these changes
Looks great to me!

2023-02-15 23:26 UTC, dmundra commented on common-practices-tools/security/encryption.md
> +g your browser "default search" to [DuckDuckGo](https://duckduckgo.com/) or [Ecosia](https://www.ecosia.org/) as they protects privacy and avoid the filter bubble.
Small typo here, the `g` is on a new line which is translating into a space on the site https://civicactions-handbook--1055.org.readthedocs.build/en/1055/common-practices-tools/security/encryption/#private-browsing.

2023-02-15 23:26 UTC, dmundra requested changes
Small typo fix needed.

2023-02-16 00:23 UTC, openprivacy commented
@dmundra I see "This branch is out-of-date with the base branch" and an "Update branch" button. Should I push that? If so, merge or rebase?

2023-02-16 02:57 UTC, dmundra commented
> @dmundra I see "This branch is out-of-date with the base branch" and an "Update branch" button. Should I push that? If so, merge or rebase?

@openprivacy, ya go for that and I recommend the default 'merge' option.

2023-02-16 02:57 UTC, dmundra approved these changes
Thanks for fixing the typo.

2023-02-16 03:34 UTC, merged