Create Innovation
CivicActions/guidebook pull request #1076
Opened 2023-03-15 16:23 UTC by hhartingrex

First draft on a new page under Project Management

2023-03-15 20:53 UTC, farooqzakhilwal approved these changes
looks great. Just minor edits. @hhartingrex leaving this for you to merge.

2023-03-16 20:49 UTC, dmundra requested changes
Need changes to the filename and added to the navigation code block.

2023-03-16 20:49 UTC, dmundra commented on practice-areas/project-management/Innovation
@hhartingrex looks like the filename needs to be 'innovation.md' so that the page loads. Also since this is a new page it needs to be added to `https://github.com/CivicActions/guidebook/blob/master/.config/mkdocs.yml#L170`

2023-03-17 16:03 UTC, dmundra approved these changes

2023-03-17 16:04 UTC, merged