Create accessibility-guidelines
CivicActions/guidebook pull request #1327
Opened 2023-12-12 21:15 UTC by kristenjernigan

Create start of accessibility guidelines page for project management practice area

2023-12-13 16:50 UTC, dmundra requested changes

2023-12-13 16:50 UTC, dmundra commented on practice-areas/project-management/accessibility-guidelines
@kristenjernigan sorry if this is too early a review. The filename is missing the extension '.md'. After you make that change you see some additional prompts to add the new file to navigation and so on. Let me know if you would like any help with that.

2024-02-07 17:17 UTC, dmundra commented on practice-areas/project-management/accessibility-guidelines
@kristenjernigan I fixed the extension of the file and made some minor updates.

2024-03-05 00:00 UTC, grugnog requested changes
I think it would be worth considering the purpose/location of this page - it seems like best accessibility practices for meetings should be common to all meetings, not just ones created by project managers?
I am also not sure we want captions always enabled, but rather that people can enable them when preferred or set them to always be on in their settings. Both of these are already always true for CivicActions Zoom meetings.
Camera to default on also has some accessibility nuance, probably better to link to this page instead: https://guidebook.civicactions.com/en/latest/company-policies/new-hire-orientation/video-call-best-practices/

2024-07-08 20:51 UTC, dmundra commented
Double checked with @kristenjernigan that this is no longer needed.

2024-07-08 20:51 UTC, closed without merging