Create sustainability.md
CivicActions/guidebook pull request #1386
Opened 2024-06-03 16:54 UTC by mgifford

Initial draft for a sustainability policy.

2024-06-03 21:06 UTC, dmundra requested changes
Our lint checker reported some issues that should be address. @mgifford please review the messages in the 'Files changed' tab.

2024-06-04 19:36 UTC, dmundra commented on company-policies/sustainability.md
> +-   Our ecosystem is interdependent
@mgifford sorry about this. Looks like we need to adjust configuration for our remark linter https://github.com/remarkjs/remark-lint/blob/main/packages/remark-lint-list-item-indent/readme.md#recommendation

2024-06-04 22:16 UTC, dmundra commented on .config/mkdocs.yml
> +      - company-policies/sustainability.md
@mgifford the new page is in the company-policies path but the menu is under 'Our practices and tools'. Which section should it be in?

2024-06-04 22:20 UTC, dmundra commented on company-policies/sustainability.md
> +-   Our ecosystem is interdependent
@grugnog do you know what might be doing this? pre-commit keeps switching the spacing from 1 space to 3 total spaces.

2024-06-04 22:30 UTC, dmundra commented on company-policies/sustainability.md
> +-   Our ecosystem is interdependent
Ah it is pre-commit and prettier that is messing with this.

2024-06-06 00:40 UTC, dmundra commented on company-policies/sustainability.md
> +-   Our ecosystem is interdependent
I think updating remark-lint-list-item-indent will fix this but I need to test it some more.

2024-06-06 14:43 UTC, dmundra commented on company-policies/sustainability.md
> +-   Our ecosystem is interdependent
This is resolved and I also put the remark updates in #1388 so it can be merged separately

2024-06-06 14:52 UTC, dmundra commented on .config/mkdocs.yml
> +      - company-policies/sustainability.md
I am will update this.

2024-06-19 01:59 UTC, elizabethraley approved these changes

2024-06-19 02:08 UTC, dmundra approved these changes

2024-06-19 16:08 UTC, merged