Remove references to accman/pull_keys.
CivicActions/guidebook pull request #251
Opened 2017-10-04 21:59 UTC by grugnog

2017-10-04 23:37 UTC, openprivacy requested changes
Thanks for this update! See comment, and please bump the version number at the top to `1.1.2`

2017-10-04 23:37 UTC, openprivacy commented on docs/03-policies/security.md
> +* SSH, SFTP and SCP access to vhosts should only ever be managed by designated admin(s). Access by password, manually installed SSH keys (other than by admins), web based "shell" script, port forward
For clarity and conciseness: replace "_should only ever be managed_" with "_are managed exclusively by_"

2017-10-19 20:02 UTC, openprivacy approved these changes

2017-10-19 20:05 UTC, openprivacy approved these changes
Looks great - thanks!

2017-10-20 14:14 UTC, kevwalsh commented
@openprivacy looks like you approved but forgot to merge? or are there further changes needed?

2017-10-20 16:36 UTC, openprivacy commented
@kevwalsh I reviewed and accepted, but no place to merge? (I'd merge if I could...) Page says"Code owner review required" - an I missing something?

2017-10-20 20:21 UTC, kevwalsh commented
@openprivacy i'll merge this, and i'll look into why you couldn't. i guess cause you're not a member of the docs or management team, and one of the files touched is /docs/03-policies/security.md ... we should make you a codeowner of that file in particular.  Changes to anything in /docs/03-policies must be approved by someone in mgmt.

2017-10-20 20:22 UTC, kevwalsh approved these changes

2017-10-20 20:22 UTC, merged