add CA believes in FOSS list, remove todo language
CivicActions/guidebook pull request #475
Opened 2019-05-15 21:44 UTC by akaroleff

2019-05-20 22:26 UTC, erogray commented on docs/01-welcome-to-civicactions/training/intro-open-source.md
> +CivicActions uses and works with FOSS whenever possible, and we believe in becuase
small typo: becuase should be because
```suggestion
CivicActions uses and works with FOSS whenever possible, and we believe in because
```

2019-05-20 22:27 UTC, erogray requested changes
small typo

2019-05-21 15:45 UTC, openprivacy commented
This looks good - thank you.
Two ideas for future edits:
1. F/LOSS (Free/Libre Open Source Software)
2. FOSS is arguably more secure _when well vetted by an active community_

2019-05-21 15:46 UTC, openprivacy approved these changes
Looks good

2019-05-21 15:47 UTC, openprivacy approved these changes
Looks good

2019-05-21 15:49 UTC, openprivacy approved these changes

2019-05-21 15:54 UTC, erogray approved these changes

2019-05-21 15:54 UTC, merged