Update to holiday
CivicActions/guidebook pull request #764
Opened 2021-11-08 13:58 UTC by elizabethraley

If holiday is on a weekend, we observe on Monday for Canada

[//]: # (rtdbot-start)

URL of RTD document: https://civicactions-handbook.readthedocs.io/en/elizabethraley-patch-1/ ![Documentation Status](https://readthedocs.org/projects/civicactions-handbook/badge/?version=elizabethraley-patch-1)

[//]: # (rtdbot-end)

2021-11-16 23:04 UTC, grugnog approved these changes

2021-11-16 23:06 UTC, grugnog requested changes, later dismissed

2021-11-16 23:06 UTC, grugnog commented on docs/045-employee-handbook-ca/benefits-and-holidays.md
> +If a holiday falls on a the weekend, the Ontario office observes on the Monday for the holiday.
@elizabethraley "observes on the Monday for the holiday" isn't clear to me? Should this be "observes the holiday on the following Monday"?

2022-04-25 20:01 UTC, marctjones approved these changes

2022-04-27 15:13 UTC, marctjones approved these changes

2022-04-27 15:59 UTC, merged