A bunch of commits, mostly high level clean-up
CivicActions/guidebook pull request #81
Opened 2017-03-27 21:42 UTC by jenharris

Removed dead links.
Updated some file Titles.

2017-03-27 23:14 UTC, grugnog requested changes

2017-03-27 23:14 UTC, grugnog commented on CHANGELOG.md
> -# <a name="changelog"></a>CHANGE LOG
I wonder if we should remove this? Whilst git does have super-detailed logs that people can parse through, I think some kind of summary of major changes (especially things to do with our employment policies) would be a good idea, especially since I expect people will still need to sign to confirm receipt from time to time - @jhr1844 may have thoughts on this also.

2017-03-27 23:14 UTC, grugnog commented on docs/policies/conduct-behavior.md
> -We follow the platinum rule at CivicActions. The golden rule is to do to others as you would have them do to you. The platinum rule is to do to others as they would like to have done to them. This re
This para doesn't seem to be in the longer version

2017-03-27 23:14 UTC, grugnog commented on docs/engineering/devops.md
> -# Development Process Overview
I am not sure "DevOps" is the right word here as it is much broader than the content on this page. I think the original title or something like "Development and Hosting Environments" might be clearer.

2017-03-27 23:24 UTC, jenharris commented on CHANGELOG.md
> -# <a name="changelog"></a>CHANGE LOG
I removed it in a later commit

2017-03-27 23:29 UTC, jenharris commented on docs/policies/conduct-behavior.md
> -We follow the platinum rule at CivicActions. The golden rule is to do to others as you would have them do to you. The platinum rule is to do to others as they would like to have done to them. This re
Added it in

2017-03-27 23:30 UTC, jenharris commented on docs/engineering/devops.md
> -# Development Process Overview
Noted and updated README TOC and file title to "Development and Hosting Environments"

2017-03-27 23:34 UTC, grugnog commented on CHANGELOG.md
> -# <a name="changelog"></a>CHANGE LOG
Not following - do you mean you re-added it? If so, I don't see it in the commits so far :)

2017-03-28 14:13 UTC, jenharris commented on CHANGELOG.md
> -# <a name="changelog"></a>CHANGE LOG
I misunderstood your comment - I can add the CHANGELOG back, though I think it should be a clean slate - the changes that were in there before were not CivicActions related

2017-03-28 18:34 UTC, grugnog commented on CHANGELOG.md
> -# <a name="changelog"></a>CHANGE LOG
The content in https://github.com/CivicActions/handbook/blob/master/CHANGELOG.md is the changelog from CivicActions handbook (the Google Drive one).

2017-03-28 19:11 UTC, jenharris commented on CHANGELOG.md
> -# <a name="changelog"></a>CHANGE LOG
Got it, I didn't realize that. I'll add it back!

2017-03-28 21:29 UTC, grugnog approved these changes

2017-03-28 21:29 UTC, merged