Add info about new employee tech stipend options
CivicActions/guidebook pull request #828
Opened 2022-04-05 15:19 UTC by jrozra200

2022-04-05 15:22 UTC, dmundra commented on docs/040-employee-handbook-us/tech-stipend.md
> +[^1]: If you or one of your employees are within the ninety-day Introductory Period, do not have equipment that is satisfactory to complete your defined role, and would benefit from recieving your Te
Thanks @jrozra200. Tiny typo, 'recieving' => 'receiving'

2022-04-05 15:24 UTC, jrozra200 commented on docs/040-employee-handbook-us/tech-stipend.md
> +[^1]: If you or one of your employees are within the ninety-day Introductory Period, do not have equipment that is satisfactory to complete your defined role, and would benefit from recieving your Te
just fixed it!

2022-04-05 15:26 UTC, jrozra200 commented
@dmundra - I'm not sure I am understanding what is failing now? Can you help me understand how to fix the remark-lint failure?

2022-04-05 16:09 UTC, dmundra commented
> @dmundra - I'm not sure I am understanding what is failing now? Can you help me understand how to fix the remark-lint failure?

@jrozra200 if you jump to 'Files changed' tab in GitHub you can see the remark-lint errors. It is complaining about `undefined definition` for some reason and read the docs did not generate a version we can review so 🤷🏾

2022-04-05 17:33 UTC, jrozra200 commented
@dmundra - looks like I can't hyperlink to the comment below. Let me know if this works for you.

2022-04-05 17:45 UTC, dmundra commented
> @dmundra - looks like I can't hyperlink to the comment below. Let me know if this works for you.

@jrozra200 looks like I found a footnote example https://github.com/readthedocs/sphinx_rtd_theme/blob/master/docs/demo/demo.rst#footnotes for readthedocs, do you want to try that?

2022-04-05 17:59 UTC, dmundra commented
@jrozra200 we can ignore the remark-lint and merge and see how this looks on handbook.

2022-04-05 17:59 UTC, dmundra approved these changes

2022-04-11 21:19 UTC, mgifford commented
Why is the docs/050-how-we-work/tools/github.md page edited here? This isn't related to the tech stipend. 

Think it might conflict or overwrite what is here https://github.com/CivicActions/handbook/pull/829

2022-04-11 23:23 UTC, dmundra commented
> Why is the docs/050-how-we-work/tools/github.md page edited here? This isn't related to the tech stipend.
> 
> Think it might conflict or overwrite what is here #829

@mgifford it is a side-effect of merging changes and auto-rebasing this branch. Sometimes commits from other merges appear in here with the pre-commit. I think this should merge fine when it is approved.

2022-04-18 20:33 UTC, thejuliekramer commented on docs/040-employee-handbook-us/tech-stipend.md
> +<sup>1</sup>: If you or one of your employees are within the ninety-day Introductory Period, do not have equipment that is
replace employee with team member

2022-04-18 22:41 UTC, jrozra200 commented
@thejuliekramer and @elizabethraley - updates ready for your review.

2022-04-21 23:12 UTC, dmundra commented
> Why is the docs/050-how-we-work/tools/github.md page edited here? This isn't related to the tech stipend.
> 
> Think it might conflict or overwrite what is here #829

@mgifford rebasing again removed the extra changes so ya just a rebasing oddity is what you noticed.

2022-04-22 21:14 UTC, elizabethraley approved these changes

2022-04-27 15:08 UTC, marctjones requested changes
Jake,

Thanks for this suggestion. Can you cancel this PR request, and I will look at incorporating the spirit of this change into the handbook.

2022-04-27 15:11 UTC, marctjones commented
Closing PR. But noting the wording change suggested. I will look into incorporating the suggested wording change into the handbook.

2022-04-27 15:11 UTC, closed without merging