Adding Tech Lead Role Description document to handbook
CivicActions/guidebook pull request #854
Opened 2022-06-20 15:50 UTC by dmundra

Deploying the doc https://docs.google.com/document/d/1usq9EHTcyoZ90DBpQp-7jPbSLwcBav06nqE9_QbFLEQ/edit# to the handbook.

2022-06-20 15:58 UTC, dmundra commented
What the new page looks like: https://handbook.civicactions.com/en/dmundra-patch-2/060-engineering/tech-lead/

2022-06-21 15:31 UTC, andyhawks commented
@grugnog @dmundra Do we want to emphasize 'project role' wherever we say 'role' here?

2022-06-22 02:41 UTC, dmundra commented
> @grugnog @dmundra Do we want to emphasize 'project role' wherever we say 'role' here?

@andyhawks I added project role emphases in paragraphs. Let me know if I missed a spot.

2022-06-30 16:59 UTC, grugnog requested changes

2022-06-30 16:59 UTC, grugnog commented on docs/060-engineering/tech-lead.md
> +## Technical Leadership Project Roles at CivicActions
I would suggest we take out the TA, TTL and SA roles for now, since they aren't being used (AFAIK) and the terminology/descriptions don't line up with (at least my understanding of) industry norms, so I think it has potential to confuse folks.
For a role that is a technical lead of a program (comprising multiple teams, each with their own TL) I would suggest a term like Technical Program Lead, perhaps - we could come back to that though, I think.

2022-06-30 17:16 UTC, dmundra commented on docs/060-engineering/tech-lead.md
> +## Technical Leadership Project Roles at CivicActions
Works for me. Done!

2022-06-30 17:17 UTC, grugnog approved these changes
Looks good now, I think!

2022-06-30 17:20 UTC, merged