Enable collapsible nav.
CivicActions/guidebook pull request #912
Opened 2022-11-09 16:33 UTC by grugnog

2022-11-10 18:51 UTC, dmundra approved these changes
Works https://handbook.civicactions.com/en/collapsiblenav/050-how-we-work/practice-areas/!

But has the same issues as the current navigation (the menu doesn't stay active, and bounces back to the top).

2022-11-16 17:14 UTC, dmundra commented on mkdocs.yml
> +  collapse_navigation: true
Discussed with @grugnog that we want to keep other changes in this PR but revert the `collapse_navigation` change.

2022-11-16 17:14 UTC, dmundra requested changes
Left a comment about reverting the collapse navigation change.

2022-11-19 00:13 UTC, dmundra commented
@grugnog you disabled the collapsible nav but it still is appearing on the branch site https://handbook.civicactions.com/en/collapsiblenav/000-contributing/docs-governance/. Maybe those lines have to be removed completely?

2022-11-21 18:49 UTC, dmundra requested changes
Left a comment https://github.com/CivicActions/handbook/pull/912#issuecomment-1320687598

2022-12-02 16:07 UTC, dmundra commented
Interesting, even after removing the collapsiblenav and reverting mkdocs.yml completely this version https://handbook.civicactions.com/en/collapsiblenav/ still displays the collapsiblenav feature. Is the branch name causing it (doubt it), is it some extreme caching?

@grugnog thoughts? Maybe new PR for the changes and close this one?

2022-12-02 16:17 UTC, dmundra commented on .readthedocs.yaml
> +    python: "3.9"
Hmm maybe it is the version of python and mkdocs that is the issue.

collapsiblenav build: https://readthedocs.org/projects/civicactions-handbook/builds/18803675/

vs

another PR build: https://readthedocs.org/projects/civicactions-handbook/builds/18782556/

2022-12-02 16:35 UTC, dmundra commented on requirements.in
> +mkdocs==1.4.2
Version of mkdocs is definitely buggy causing `collapse_navigation: false` to not work.

2022-12-08 00:46 UTC, grugnog commented
After playing with this, it seems like the upgrade changes quite a few things in unexpected ways and rather than figure out which we want to keep/drop etc I ported these changes to https://github.com/CivicActions/handbook/pull/926 which is the direction the design team is looking at going forward.

2022-12-08 00:46 UTC, closed without merging